#!/bin/sh

exec 2>&1

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/sbin:/sbin

echo "3 2 1 ..."
sleep 3
DIR=/server/ardina/src

cd ${DIR} && exec setuidgid nobody node WEB.js
